### ISSUE TITLE
Don't report for .g.cs files

### ISSUE THREAD

**Issue by ljw1004** [microsoft/RoslynClrHeapAllocationAnalyzer#25]
The XAML .g.cs files can't be modified by the user. So there's nothing to be gained by reporting on them.

**Comment by mjsabby** [comment]
Suppose taking it further is for all compiler generated files don't run it at all.

**Comment by ljw1004** [comment]
I think there are two ways to detect compiler-generated code...

1. There's a widespread convention that .g.cs indicates a compiler-generated file
2. There's the [CompilerGeneratedAttribute](https://msdn.microsoft.com/en-us/library/system.runtime.compilerservices.compilergeneratedattribute(v=vs.110).aspx) attribute.

**Comment by edespong** [comment]
I think this would be quite straight forward to implement. I would, however, implement this after (if decided to pull) #22, because:

1. The implementation of this issue would touch a lot of places where #22 makes changes, which will cause a lot of merge issues
2. It makes sense that this would be configurable both for the file endings, e.g. a comma separated list of patterns to ignore (default: *.g.cs) and for which attributes to ignore, for example [CompilerGeneratedAttribute](https://msdn.microsoft.com/en-us/library/system.runtime.compilerservices.compilergeneratedattribute%28v=vs.110%29.aspx) and [GeneratedCodeAttribute ](https://msdn.microsoft.com/en-us/library/system.codedom.compiler.generatedcodeattribute(v=vs.110).aspx)

**Comment by mjsabby** [comment]
@edespong thanks for your work on all other issues. I'm willing to take a look at this if you can bring a PR to master.

I'm trying to get a new VSIX out in a couple of weeks.

**Comment by edespong** [comment]
@mjsabby I will start with fixing the merge error for the pull requests and then adding a PR for #22. If I get time before the new VSIX I will try to fix this one.

**Comment by edespong** [comment]
I now have a working version of this at [Issue25_NoReportOnGeneratedCode](https://github.com/edespong/RoslynClrHeapAllocationAnalyzer/tree/Issue25_NoReportOnGeneratedCode).

It has merged from the #46 in order to get settings. If/when #46 is accepted, I will create a new pull request with this change.

![image](https://user-images.githubusercontent.com/1311589/38151693-9af244a6-3464-11e8-8b8c-81df42691bda.png)

**Comment by vchirikov** [comment]
@edespong when we have this settings?

**Comment by edespong** [comment]
@vchirikov It depends on whether the pull request for options is accepted.

I think it would be nice to have configurable file name patterns, but if it does not get accepted it should be easy to extract the relevant code changes and hard code '*.g.cs'.

If you want to try it out now, the branch referred to above is in a good state.

**Comment by edespong** [comment]
This issue is now fixed without a dependency on the large VsOptions branch, [PR here](https://github.com/Microsoft/RoslynClrHeapAllocationAnalyzer/pull/59).

**Comment by cezarypiatek** [comment]
Hi @mjsabby
I think this issue should be closed - #59 has been merged.
