### ISSUE TITLE
[Help Wanted] Meaning behind 'Non-ValueType enumerator may result in heap allocation'.

### ISSUE THREAD

**Issue by JimmyDeemo** [Microsoft/RoslynClrHeapAllocationAnalyzer#56]
I see this occasionally in my code base, and while I believe the analyser that there could be an allocation here, I just wondered if someone could explain to me where the allocation might occur such that I could make an informed decision on whether to change the code or not.

i.e. What is it about returning reference type implementors of the `IEnumerator` interface that might cause an allocation?

**Comment by edespong** [comment]
Looking at two examples:
```
IList<int> data = new[] { 1 }.ToList();
foreach (var i in data) { }
```

and

```
List<int> data= new[] { 1 }.ToList();
foreach (var i in data) { }
```
The first one will give a warning because `IList<T>` will return a `System.Collections.Generic.IEnumerator<T>` when `GetEnumerator` in the for loop, which could be an object allocated on the heap.

In the second case of `List<T>` the return type of `GetEnumerator` is a `List<T>.Enumerator` which is a struct, resulting in no warning.

**Comment by JimmyDeemo** [comment]
I see, so it's an indication into the hidden implementation behind `IEnumerator` implementations.

Thanks for breaking it down.

**Comment by edespong** [comment]
List. You can hover the variable in Visual Studio to see what the compiler determines it to be.
